### ISSUE TITLE
subghz S2868A2_CLI example does not wor on nucleo f401RG

### ISSUE THREAD

**Issue by tobbad** [STMicroelectronics/x-cube-subg2#10] opened 2024-01-07 14:44 UTC
**Caution**

The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus) or in the [ST Community/Q&A Topics](https://community.st.com/s/topiccatalog).

**Describe the set-up**

 * Nucleo-f401RE
 * x-cube-subg1 
 * running Project S2868A2_CLI example on NUCLEO-f401RE from the project source as it is.
 * CubeIDE 1.14.4

**Describe the bug**
* S2LP_ManagementIdentificationRFBoard function freezes and does not Return
IN 
![grafik](https://github.com/STMicroelectronics/x-cube-subg2/assets/6281553/94cf9b21-a2a8-4eb6-b920-3c8780a7db13)
[freeze_readregisters_on_s2lp.csv](https://github.com/STMicroelectronics/x-cube-subg2/files/13853847/freeze_readregisters_on_s2lp.csv)
* On the SPI  Bus I see the data shown i the attached file 

**How To Reproduce the bug**
Run the example

**Additional context**
I can not understand what I did wrong as obvious this Project is used (probably) by others.

![Screenshot_20240107_153035](https://github.com/STMicroelectronics/x-cube-subg2/assets/6281553/ae38d821-1716-4049-b7b9-0129b0e829cc)

**Comment by tobbad** [comment] 2024-01-07 16:22
This is true if I start any Project  (TX, RX, Border_router, SnifferUDP Server and client). In all these Projjects MX_X_CUBE_SUBG2_Init() is not left.At least in the sniffer project, I would assume that this should happens.

**Comment by mgrella** [comment] 2024-01-08 09:48
Hello @tobbad ,

thank you for reporting the issue. I'll look into it and let you know as soon as possible.

BR,
Marco

**Comment by mgrella** [comment] 2024-01-08 13:54
Hello @tobbad ,

I am not able to reproduce your issue, both with pre-built binary and recompiled code. I am using NUCLEO-F401RE with X-NUCLEO-S2868A2 mounted on it. Is this your setup?
Could you please try to:
 - flash your board with the pre-built binary (Projects\NUCLEO-F401RE\Examples\S2868A2_CLI\Binary\S2868A2_CLI.bin) and see if it works, you can verify this using the S2-LP DK GUI as described in the readme.html or simply using Teraterm: writing "help" in the console will make the firmware output some information:
 - If the above is not working there might be some issue with you hardware, can you check that no jumpers have been removed? JP1 on the X-NUCLEO must be fit, JP6 on the NUCLEO must be fit. Can you try different NUCLEO/X-NUCLEO and/or can you try to perform a full chip erase?

Please let me know if you make any progress,
best regards,
Marco

**Comment by mgrella** [comment] 2024-02-01 16:16
Hello @tobbad , do you have any updates?
Are you still facing this issue?

BR,
Marco

**Comment by mgrella** [comment] 2024-02-23 09:17
Hello @tobbad , I am going to close this issue.
If you are still facing this problem, please let me know and we'll investigate more.

BR,
Marco

**Closed as not planned by mgrella** 2024-02-23 09:17 UTC
